- name: install shipping component
  hosts: shipping
  become: yes
  vars:
    mysql_password: RoboShop@1
  tasks:

  - name: install maven
    ansible.builtin.dnf:
      name: maven
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download shipping application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp

  - name: extract shipping application
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command:
      cmd: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command:
      cmd: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: reload systemd and start shipping service
    ansible.builtin.systemd:
      daemon_reload: true
      name: shipping
      state: started
      enabled: yes

  - name: install mysql client
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: ensure schema directory exists
    ansible.builtin.file:
      path: /app/schema
      state: directory

  - name: copy shipping SQL schema file
    ansible.builtin.copy:
      src: files/shipping.sql
      dest: /app/schema/shipping.sql

  - name: check cities schema exists or not
    ansible.builtin.command:
      cmd: >
        mysql -h mysql.forpractice.uno -uroot -p{{ mysql_password }} -sN -e
        "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
    register: schema

  - name: print schema check output
    ansible.builtin.debug:
      msg: "Schema check output: {{ schema.stdout }}"

  - name: load cities data
    ansible.builtin.shell:
      cmd: mysql -h mysql.forpractice.uno -uroot -p{{ mysql_password }} < /app/schema/shipping.sql
    when: schema.stdout != "1"

  - name: restart and enable shipping service
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes
