- name: install shipping component
  hosts: shipping
  become: yes
  vars:
    mysql_password: RoboShop@1
  tasks:
  - name: install maven
    ansible.builtin.dnf:
      name: maven
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download shipping application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp/shipping.zip

  - name: extract shipping application
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: ensure schema directory exists
    ansible.builtin.file:
      path: /app/schema
      state: directory

  - name: check if shipping.sql exists
    ansible.builtin.shell: ls -l /app/schema/shipping.sql
    register: sql_file_exists
    ignore_errors: yes

  - name: fail if shipping.sql is not found
    ansible.builtin.fail:
      msg: "shipping.sql is missing from /app/schema/"
    when: sql_file_exists.rc != 0

  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: daemon reload and start shipping service
    ansible.builtin.systemd:
      name: shipping
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: install mysql client
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: check if cities schema exists
    ansible.builtin.command: |
      mysql -h mysql.forpractice.uno -uroot -p{{ mysql_password }} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
    register: schema

  - name: print schema output
    ansible.builtin.debug:
      msg: "Schema output: {{ schema.stdout }}"

  - name: load cities data if schema does not exist
    ansible.builtin.shell: "mysql -h mysql.forpractice.uno -uroot -p{{ mysql_password }} < /app/schema/shipping.sql"
    when: schema.stdout != "1"

  - name: start and enable shipping service
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes
